data:
  text_corpus_path: "data/raw/text/"
  synthetic_audio_path: "data/processed/audio/"
  target_language: "uz"  # Uzbek as example low-resource language
  sample_rate: 16000
  max_duration: 30.0

tts:
  model: "coqui-tts"
  language: "uz"
  speaker_id: null
  voice: "default"

whisper:
  model_name: "openai/whisper-small"
  batch_size: 16
  learning_rate: 1e-5
  num_epochs: 10
  warmup_steps: 500
  gradient_accumulation_steps: 2

augmentation:
  enabled: true
  noise_factor: 0.005
  speed_range: [0.9, 1.1]
  pitch_shift_range: [-2, 2]

training:
  seed: 42
  device: "cuda"
  output_dir: "models/"
  logging_steps: 100
  evaluation_steps: 500
  save_steps: 1000
  
wandb:
  project: "whispertune"
  entity: null  # Your wandb username/organization
